### ISSUE TITLE
Terramap Online too laggy

### ISSUE THREAD

**Issue by infernalcombat** [TerraMap/terramap.github.io#11]
So I'm just tired of looking for Plantera Bulbs, but every time I load my expert 1.3.5.3 world, it simply just crashes the webpage and says "Aw, snap!" A little help here?

**Comment by jasoncoon** [comment]
1. What OS (Windows, Mac, Linux)?
2. What browser (Chrome, FireFox, Opera, Edge, IE)?
3. What world size (small, medium, large)?
4. Mind zipping up and attaching the world file?

I've tested primarily with Chrome on Windows and Mac.  Although I have tested FireFox and Edge on Windows, I haven't done it in a while.
