### ISSUE TITLE
Targeting a tile uses right click but still shows the context menu

### ISSUE THREAD

**Issue by flying-sheep** [TerraMap/terramap.github.io#14]
I think either left click should show the target for a tile or right click should block the context menu. I’d prefer left click.

It’s possible in JS to make left click work while still allowing click&drag to pan the view.

**Comment by jasoncoon** [comment]
Yeah, left click used to work, not sure why it doesn't now.  Allowing right click was a short-term hack: https://github.com/TerraMap/terramap.github.io/commit/38c1463a3d357003c19bf38084d70d4f7f129803#diff-66a2ddfb5a8fa56f8e913c989a19ef5a

**Comment by flying-sheep** [comment]
easy, because jquery.panzoom does `e.stopPropagation()`

what we can do instead is using the [panzoomed event](https://github.com/inuyaksa/jquery.panzoom#panzoomend), which is explicitly documented to be able to handle clicks using its `changed` parameter.

**Comment by jasoncoon** [comment]
Should be fixed now, thank you!

**Comment by flying-sheep** [comment]
great!
