### ISSUE TITLE
Cannot read beyond the end of the stream

### ISSUE THREAD

**Issue by TuRan-sino** [TerraMap/terramap.github.io#25]
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.ReadString()
   在 TerraMap.Data.World.ReadHeader(BinaryReader reader, Boolean skipVersion) 位置 C:\Users\Jason\source\terramap\windows\Data\World.cs:行号 633
   在 TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) 位置 C:\Users\Jason\source\terramap\windows\Data\World.cs:行号 455
   在 TerraMap.Data.World.Read(String filename) 位置 C:\Users\Jason\source\terramap\windows\Data\World.cs:行号 438
   在 TerraMap.Data.World.<>c__DisplayClass382_0.<ReadAsync>b__0() 位置 C:\Users\Jason\source\terramap\windows\Data\World.cs:行号 400
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 TerraMap.MainWindow.<Open>d__24.MoveNext() 位置 C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:行号 308
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 TerraMap.MainWindow.<Open>d__23.MoveNext() 位置 C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:行号 275
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 TerraMap.MainWindow.<OnSelectedWorldFileChanged>d__61.MoveNext() 位置 C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:行号 1266
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jasoncoon** [comment]
This should be fixed now, thanks!
