### ISSUE TITLE
Incorrect tile details

### ISSUE THREAD

**Issue by VOID404** [TerraMap/terramap.github.io#26]
Terramap finds renders random items in random places. I am using vanilla 1.4.3.1

![Screenshot_2021-11-24_17-36-58](https://user-images.githubusercontent.com/9433601/143278922-a0a305e4-68e3-4ae2-8d6f-cd176d994e36.png)

**Comment by VOID404** [comment]
It looks like the map is rendered mostly correctly, but tile details are incorrect. The app sees `nothing` where something is, and something (like gold on the screenshot) where it is not

**Comment by VOID404** [comment]
The white strips rendered incorrectly on the map throw errors in the console
![Screenshot_2021-11-24_18-11-08](https://user-images.githubusercontent.com/9433601/143284291-d86df563-0307-4233-aedc-593ee5da822f.png)

**Comment by jasoncoon** [comment]
Likely caused by tiles that I haven't updated/added yet. I don't suppose you can zip up and attach the world file?

**Comment by VOID404** [comment]
[the_cherry.zip](https://github.com/TerraMap/terramap.github.io/files/7599257/the_cherry.zip)

**Comment by jasoncoon** [comment]
Fixed, thanks!
