### ISSUE TITLE
Website glitches side of map

### ISSUE THREAD

**Issue by zaczumba** [TerraMap/terramap.github.io#27]
I don't know where I should put this so I'm putting this here, my main world for some reason the right side gets pulled up way too high and I can't see anything coherent on that side. My world doesn't look like this as I haven't done any major renovations there. It also looks like the blocks are stretched.
![image](https://user-images.githubusercontent.com/68793231/145963798-26201dbc-5980-4e6a-bf75-93b055931d20.png)

**Comment by jasoncoon** [comment]
Thanks for the bug report. Can you zip up and upload the world file to this issue?

**Comment by jasoncoon** [comment]
This should be fixed now.
