### ISSUE TITLE
Broken in v1.4.4

### ISSUE THREAD

**Issue by Nekohime1989** [TerraMap/terramap.github.io#31]
Please fix

**Comment by LesserWords** [comment]
To be clear, it still loads maps created before the update correctly but, when loading maps created after the update its stays at "Reading world header..." permanently.

**Comment by jasoncoon** [comment]
OK, I've fixed **some** problems loading Terraria v1.4.4 worlds. I have not yet added any of the new tiles or items. Please let me know if you find any other problems.

**Comment by mmachaka** [comment]
The downloadable version is missing the executable file. But I loaded 10+ worlds on https://terramap.github.io/ without issues. Thank you very much!

**Comment by windwingwood** [comment]
I've problem with my v1.4.3 old map, WorldLoader.js in line 208 should add version checking.
--------------------------------------------------
world.afterPartyOfDoom = reader.readUint8() > 0;

**Comment by jasoncoon** [comment]
@windwingwood TerraMap web and TerraMap Windows v1.4.14 only support the latest version of Terraria (v1.4.4.1). Either load the world in Terraria v1.4.4.1 (which will update it to the latest version), or try downloading and using an older version of TerraMap Windows: https://terramap.github.io/windows.html
