### ISSUE TITLE
Tiles not being there

### ISSUE THREAD

**Issue by obsidian-golden** [TerraMap/terramap.github.io#32]
A lot of the tiles added in 1.4.4 aren't present yet, some examples include:
ash grass
ash trees
ash wood
corrupted mud
the dirtiest dirt
and more that i did not found
 
also the new liquid is seen as water

**Comment by jasoncoon** [comment]
I've added all of the new tiles, items, etc. I still need to define colors for them all, but you should at least be able to search for them now.

**Comment by obsidian-golden** [comment]
Thank you for your hard work. o7
