### ISSUE TITLE
zoom is extremely difficult to control on chromebook with trackpad

### ISSUE THREAD

**Issue by esotericist** [TerraMap/terramap.github.io#33]
i'm not quite sure what's happening here, but when i try to use the mousewheel functionality on the trackpad on my chromebook, it seems nearly impossible to zoom in or out a small amount; it wants to go all the way in or all the way out. only the faintest of touches might do less, and usually still drastically overshoots so that you go from "can see too much" to "can't see enough".

some kind of zoom sensitivity would be nice, but a zoom hotkey (i couldn't see one mentioned in help) would probably be a simpler mitigation

**Comment by jasoncoon** [comment]
I was able to reproduce on a mac book trackpad. I just pushed a change that should help. It seems better when zooming with the two finger vertical scroll gesture. It's still way too fast when using a pinch to zoom gesture. I'll try to investigate that next.

**Comment by esotericist** [comment]
oh, that's fantastic; that is definitely usable now in the two finger version. thanks so much for the quick response, and hopefully the pinch to zoom variant isn't too complicated.

it does occur to me that a possible ideal eventuality could be a setting to use the two-finger scroll (both vertical and horizontal) to pan, then pinch to zoom, but that's obviously a deeper feature request. i'm happy enough just to be able to use this now.
