### ISSUE TITLE
World loading incorrectly in Terramap, Shows map corruption when none is present

### ISSUE THREAD

**Issue by Enkazadas** [TerraMap/terramap.github.io#35]
After adding a structure comprised of new blocks to my world, a subsequent load of the map in Terramap displays visual corruption and artifacting.
![image](https://user-images.githubusercontent.com/115683218/195500689-bc350234-ae7e-4816-af5d-30e1e45f9e59.png)
 i suspect this is due to the new Luminite bricks, of which my structure largely consists. I can also provide the world file if needed to. Hope this helps.

**Comment by jasoncoon** [comment]
Thanks for the info! I hope to have a chance to work on this soon. I haven't had a chance to play lately, and don't have any illuminant paint. I usually use Builder's Workshop maps to test with, but I haven't been able to find one updated with the latest 1.4.4 content.

A copy of the world file would help greatly, thanks!

**Comment by Enkazadas** [comment]
I've uploaded the world file to https://filebin.net/4tqvpjxz1klo2u1p . I would have send it directly but Github doesn't support the format. Hope it helps!

**Comment by jasoncoon** [comment]
Thanks for the help! I've updated the web version: https://terramap.github.io

I also added all the new item, tile, and wall names. Still haven't added colors for all the new stuff yet.

I'll work on fixing the Windows version next.

**Comment by jasoncoon** [comment]
Closing, let me know if you still have any problems, or find any new issues.
